### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by StixsmasterHD4k** [NB-Core/lotgd#19]
So the index.php seems to be fine but every time I try launching the installer I get the error 500 code followed by "Critical error while connecting to database: No such file or directory". And I have checked, the file is indeed uploaded and there. By "file" I mean the installer.php file

I haven't even been able to configurate the database information into the game yet

**Comment by NB-Core** [comment]
Ah... apologies... I didn't see your Issue....

a fix at a later stage of the installer broke the first step it seems....
Add that one Line 149 (I assume you got the latest release, snapshot should also work) before the $link:

141 // If you are running a server that has high overhead to connect to your
142 // database (such as a high latency network connection to mysql),
143 // reversing the commenting of the following two code lines may significantly
144 // increase your overall performance.  Pconnect uses more server resources though.
145 // For more details, see
146 // http://php.net/manual/en/features.persistent-connections.php
147 //
148 // Line is important for installer only, step 5
149 if (defined("IS_INSTALLER") && httpget('stage')>4)
150         $link = db_pconnect($DB_HOST, $DB_USER, $DB_PASS);

It should start then. Apologies for the oversight.

<---common.php
