### ISSUE TITLE
Missing dbwrapper.php prevents install.

### ISSUE THREAD

**Issue by digdilem** [NB-Core/lotgd#5]
./common.php has this require

require_once("lib/dbwrapper.php");

But this file does not exist. There are other dbwrapper_* files, but not this one.

This any attempt of running (in this case via cli as it gets a 500 error otherwise), results in 

```
 php installer.php
PHP Warning:  require_once(lib/dbwrapper.php): failed to open stream: No such file or directory in /var/www/lotgd/common.php on line 47
PHP Fatal error:  require_once(): Failed opening required 'lib/dbwrapper.php' (include_path='.:/usr/share/php') in /var/www/lotgd/common.php on line 47

```

**Comment by NB-Core** [comment]
You're right, sorry for the late response and Happy New Year!
It's missing in common.php, also referenced in the core files lib/taunt.php and lib/titles.php.

This is the file content, it chooses the wrapper it uses.

`<?php
// addnews ready
// translator ready
// mail ready
require_once("lib/errorhandling.php");
require_once("lib/datacache.php");
require_once("settings.php");
/* * * *
 * Avaiable values for DBTYPE:
 *
 * - mysql:                             The default value. Are you unsure take this.
 * - mysqli_oos:                The MySQLi extension of PHP5, object oriented style
 * - mysqli_proc:               The MySQLi extension of PHP5, procedural style
 *
 */
define('DBTYPE',$DB_TYPE);

$dbinfo = array();
$dbinfo['queriesthishit']=0;

//mysql is default even if gibberish is entered
switch(DBTYPE) {
        case 'mysqli_oos':
                require('./lib/dbwrapper_mysqli_oos.php');
                break;
        case 'mysqli_proc':
                require('./lib/dbwrapper_mysqli_proc.php');
                break;
        default:
                require('./lib/dbwrapper_mysql.php');
                break;

}

?>
`

**Comment by NB-Core** [comment]
Updated and did a new release. =) ty!
